### ISSUE TITLE
Error with CmakeLists files for building DRAMSys library only

### ISSUE THREAD

**Issue by NklsG** [tukl-msd/DRAMSys#13]
When building the DRAMSys library only, the subdirectory path for the nlohmann has one /library too much. It says:

CMake Error at src/common/configuration/CMakeLists.txt:36 (add_subdirectory):
  add_subdirectory given source "/home/gross/Downloads/DRAMSys
  Library/DRAMSys/DRAMSys/library/library/src/common/third_party/nlohmann"
  which is not an existing directory. 

And also the CMakeLists.txt in /DRAMSys/library/ still contains CMAKE_CXX_STANDARD 11 and not 17.

**Comment by lsteiner-tukl** [comment]
Thank you for the hint! I have added a commit that should fix the bugs.
