### ISSUE TITLE
Integration of gem5 and DRAMSys

### ISSUE THREAD

**Issue by Yicheng22** [tukl-msd/DRAMSys#16]
The integration of  current version of gem5 and DRAMSys seems need a lot of effort. 
Could you please provide a workable gem5 repo alone with the DRAMSys?

**Comment by myzinsky** [comment]
There are some patches in Review in order to integrate DRAMSys fully with gem5. 

You just have to wait until gem5 team has accepted them.

From our side we are done.

**Comment by myzinsky** [comment]
This is done since dramsys is now part of gem5
