### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by cnjsdfcy** [tukl-msd/DRAMSys#19]
Hi,

After compiled the project, the default config file "ddr5-example.json" was not found which caused a "**_Failed to open file_**" error.
After specified the config file to _DRAMSys/library/resources/simulations/ddr3-example.json_, another error came up: 
![image](https://user-images.githubusercontent.com/5670527/205624336-76e83c2f-3afa-4c68-a07f-90afc0fd2901.png)

Not sure what's wrong with the json file's format, please help take a look, thanks.

**Comment by lsteiner-tukl** [comment]
Hey,
as described in the readme you should call DRAMSys like this:
"
To run DRAMSys with a specific base config file:

$ ./DRAMSys ../../DRAMSys/library/resources/simulations/ddr3-example.json
To run DRAMSys with a specific base config file and a resource folder somewhere else to the standard:

$ ./DRAMSys ../../DRAMSys/tests/example_ddr3/simulations/ddr3-example.json ../../DRAMSys/tests/example_ddr3/
"
It seems that you did not navigate to the config file properly.

**Comment by cnjsdfcy** [comment]
Ohh, I see, the second arg for resources path is the devil.
Thanks for you quickly help.
Closing.
