### ISSUE TITLE
maybe overwrite a request from frontend for controller ?

### ISSUE THREAD

**Issue by gxflying** [tukl-msd/DRAMSys#21]
Hi sir:
     I have one more question here,  when dealing with the BEGIN_REQ phase in fuction Controller::nb_transport_fw , it will directlly assgin the new payload to the transToAcquire.payload without check wheather transToAcquire.payload is a nullptr.  
in a sernario where the first req is acccepted but has NOT been passed to scheduler by scheduler->storeRequest(),  and the second req is comming,  the implementation of current version will cause the second trans directlly overwrite the first one, and the firsrt trans(request) is lost !

am I right here, or I have missed some infomation about this

wish your reply,  thanks~

https://github.com/tukl-msd/DRAMSys/blob/09f6dcbb91351e6ee7cadfc7bc8b29d97625db8f/DRAMSys/library/src/controller/Controller.cpp#L392

**Comment by lsteiner-tukl** [comment]
Hey,
you have to take the TLM exclusion rule into consideration. The initiator is only allowed to send a new request (BEGIN_REQ) after it has received an END_REQ for the previous request. This is the way how backpressure is modelled in TLM. With this in mind you should see that transToAcquire.payload will always be nullptr when it is overwritten.
