### ISSUE TITLE
Fatal: Error in TraceRecorder: Error cannot open database

### ISSUE THREAD

**Issue by boobalan1996** [tukl-msd/DRAMSys#26]
PWD: /india/tools/DRAMSys/DRAMSys/build/bin
Command used: ./DRAMSys ../../configs/lpddr4-example.json 

<img width="426" alt="image" src="https://github.com/tukl-msd/DRAMSys/assets/139101969/f5835741-421d-4417-9644-20e78bea9589">

Please help me to fix this issue

**Comment by lsteiner-tukl** [comment]
Hey,
can you check the permissions of the folder in which DRAMSys is executed? It seems that the write permissions are missing.

**Comment by boobalan1996** [comment]
![image](https://github.com/tukl-msd/DRAMSys/assets/139101969/b5970753-7676-44c1-bb41-0b6d8c3d295a)

Write Permission is there, Could you please point out which database it's expecting?

**Comment by lsteiner-tukl** [comment]
It is not expecting a database, it tries to create one. But the directory is owned by root. You need write permissions in the directory you are executing the binary from. E.g., if you execute the binary directly in build/bin/ you need write permissions in that folder.

**Comment by boobalan1996** [comment]
Can we redirect the database creation from another directory?

**Comment by lsteiner-tukl** [comment]
The database is created in the directory you are calling DRAMSys from. So you can choose whatever directory you want. Or you can disable the database creation completely in the simconfig.

**Comment by boobalan1996** [comment]
![image](https://github.com/tukl-msd/DRAMSys/assets/139101969/f3c3500b-0bc8-4d73-9e24-13d0d013371a)
Thanks ! 
I changed the root directory permission still facing different errors, Please check and help me to fix this.

**Comment by lsteiner-tukl** [comment]
See #24

**Comment by boobalan1996** [comment]
Thanks! I hope Highlighted warning is ignorable and the simulation is working fine. 
Could you please say how to analyze through simulation & trace analyzer Tools? 

![image](https://github.com/tukl-msd/DRAMSys/assets/139101969/13dda19a-fe35-4118-bff6-425cd71006f8)

**Comment by lsteiner-tukl** [comment]
Yes, the warning is fine. A simulation creates an output SQLite trace database (.tdb) where all transactions and DRAM commands are recorded. You can either write some SQL queries to analyze the database or you can request a license for the Trace Analyzer, which provides a visualization of the database and some built-in metrics.

**Comment by boobalan1996** [comment]
Hi,
I can see only address mapping & BW information in the terminal, 
Could you please say how I can check the log files about the working of memory and controller? 
To understand better do we have the option to enable log generation? If not can we write some function to generate logs?

**Comment by lsteiner-tukl** [comment]
Could you please create a separate issue for this question? Thanks!
