### ISSUE TITLE
Fatal Error DRAM Power Analysis

### ISSUE THREAD

**Issue by boobalan1996** [tukl-msd/DRAMSys#28]
Hi,
To analyze more I enabled power analysis and debug options in the sim config, Facing a fatal error because of the DRAMPower library.
Please let me know which DRAMPower library I need to include.
![image](https://github.com/tukl-msd/DRAMSys/assets/139101969/c043c13d-f813-4633-bbf8-cc4bf2b2e92c)
![image](https://github.com/tukl-msd/DRAMSys/assets/139101969/be70b77a-c031-41dc-a3be-f33d7cea36e8)

**Comment by lsteiner-tukl** [comment]
The readme clearly says "To include DRAMPower in your build enable the CMake option DRAMSYS_WITH_DRAMPOWER.". But before you create another issue I can already tell you that DRAMPower does not support HBM2 yet.
