### ISSUE TITLE
Could not run with the .stl trace files

### ISSUE THREAD

**Issue by ctobryan** [tukl-msd/DRAMSys#41]
![image](https://github.com/tukl-msd/DRAMSys/assets/170618773/61810356-c4f1-4818-9e2c-7af2eb6a5bb8)
![image](https://github.com/tukl-msd/DRAMSys/assets/170618773/6e56ba93-04fd-41ed-825f-c20ca2af7f62)

Hi, may I ask is there any additional requirement or dependencies set up in order to simulate DRAMSys using the provided trace files, example.stl?

**Comment by myzinsky** [comment]
This might come from a malformed trace file (https://github.com/tukl-msd/DRAMSys/issues/29) or you are missing GIT LFS (https://github.com/tukl-msd/DRAMSys/issues/24)

**Comment by ctobryan** [comment]
![image](https://github.com/tukl-msd/DRAMSys/assets/170618773/60aedfc9-a8b6-421c-8d80-a8d0e6a0eaf8)
Thanks, the issue is solved.

**Comment by myzinsky** [comment]
Looks good to me :-)
