### ISSUE TITLE
Compile error with TraceAnalyzer

### ISSUE THREAD

**Issue by yulei900609** [tukl-msd/DRAMSys#49]
![image](https://github.com/user-attachments/assets/468fa5a5-0225-4f09-98d3-43a66f1c4f4d)
 How to fix this issue? thx~~

**Comment by derchr** [comment]
Hi, can you give some information on the distribution used, the Qt Version, compiler version?

**Comment by yulei900609** [comment]
> Hi, can you give some information on the distribution used, the Qt Version, compiler version?

Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
 thx~~~

**Comment by derchr** [comment]
Your Qt Version might be too old. Can you try 5.15?

**Comment by yulei900609** [comment]
> Your Qt Version might be too old. Can you try 5.15?

@derchr Qt 5.15.2 works well, thx very much.

**Comment by derchr** [comment]
You're welcome!
