### ISSUE TITLE
Where is the traceAnalyzer directory?

### ISSUE THREAD

**Issue by kopinions** [tukl-msd/DRAMSys#8]
I have seen the traceAnalyzer in the CMakeLists.txt, but no directory inside the project. Is that dir missed? Thanks

**Comment by lsteiner-tukl** [comment]
The Trace Analyzer is not open source. As mentioned in the readme please contact [Matthias Jung](mailto:matthias.jung@iese.fraunhofer.de) if you are interested in the feature.
